### ISSUE TITLE
utcOffset property constructor (not an integer)

### ISSUE THREAD

**Issue by xev-pcjc** [ChristianTremblay/BAC0#335]
I'm testing some code I'm working on using BAC0 to form a simple gateway between a machine speaking Modbus/TCP and with a BACnet network.

Testing with YABE results in a backtrace when selecting the "device" node in the explorer view. Turning on bacpypes debugging, it appears this is down to the utcOffset property. Its constructor expects an integer, but the time handler code passes a floating point (I think).

```
exception: TypeError('invalid constructor datatype')
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/bacpypes/app.py", line 382, in indication
    helperFn(apdu)
  File "/home/pi/.local/lib/python3.7/site-packages/bacpypes/service/object.py", line 308, in do_ReadPropertyMultipleRequest
    read_access_result_element = read_property_to_result_element(obj, propId, propertyArrayIndex)
  File "/home/pi/.local/lib/python3.7/site-packages/bacpypes/service/object.py", line 206, in read_property_to_result_element
    read_result.propertyValue = read_property_to_any(obj, propertyIdentifier, propertyArrayIndex)
  File "/home/pi/.local/lib/python3.7/site-packages/bacpypes/service/object.py", line 167, in read_property_to_any
    value = datatype(value)
  File "/home/pi/.local/lib/python3.7/site-packages/bacpypes/primitivedata.py", line 731, in __init__
    raise TypeError("invalid constructor datatype")
TypeError: invalid constructor datatype
```

This minor change appears to fix the issue for me...

```
diff --git a/BAC0/core/functions/TimeSync.py b/BAC0/core/functions/TimeSync.py
index 743f433..e2f4905 100644
--- a/BAC0/core/functions/TimeSync.py
+++ b/BAC0/core/functions/TimeSync.py
@@ -156,7 +156,7 @@ class TimeHandler(object):

     def utcOffset(self):
         "Returns UTC offset in minutes"
-        return self.now.astimezone().utcoffset().total_seconds() / 60
+        return int(self.now.astimezone().utcoffset().total_seconds() / 60)

     def is_dst(self):
         return self.timezone.dst(self.now) != dt.timedelta(0)
```

**Comment by xev-pcjc** [comment]
And it appears this is already fixed - guess either I have the wrong branch, or pip3 install ... version in my environment?
