### ISSUE TITLE
IP Address provided (xxx.xxx.xxx.xxx) invalid

### ISSUE THREAD

**Issue by Ferkelcode** [ChristianTremblay/BAC0#355]
Hello,

I tried bacnet = BAC0.connect(ip='xxx.xxx.xxx.xxx')

but it shows: 
BAC0.core.io.IOExceptions.InitializationError: IP Address provided (xxx.xxx.xxx.xxx) invalid. Check if another software is using port 47808 on this network interface. If so, you can define multiple IP per interface. Or specify another IP using BAC0.lite(ip='IP/mask')

Do you know what could be the reason?

I got 2 IP addresses (xxx.xxx.xxx.x47 and xxx.xxx.xxx.x48), I only know that one of them is correct for the device. But I tried both of them with bacnet = BAC0.connect(ip='xxx.xxx.xxx.xxx'). 

For xxx.xxx.xxx.x47,  it shows: 
2022-10-09 13:41:24,798 - INFO    | Starting BAC0 version 21.12.03 (Complete)
2022-10-09 13:41:24,798 - INFO    | Use BAC0.log_level to adjust verbosity of the app.
2022-10-09 13:41:24,798 - INFO    | Ex. BAC0.log_level('silence') or BAC0.log_level('error')
2022-10-09 13:41:24,798 - INFO    | Starting TaskManager
2022-10-09 13:41:24,813 - INFO    | Using ip : xxx.xxx.xxx.**39**
Traceback (most recent call last):
  File "C:\Users\mmg-yho\PycharmProjects\bac0_test\main.py", line 8, in <module>
    bacnet = BAC0.connect(ip='xxx.xxx.xxx.x47')
  File "C:\ProgramData\Anaconda3\lib\site-packages\BAC0\scripts\Complete.py", line 170, in __init__
    Lite.__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\BAC0\scripts\Lite.py", line 152, in __init__
    Base.__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\BAC0\scripts\Base.py", line 143, in __init__
    raise InitializationError(
BAC0.core.io.IOExceptions.InitializationError: IP Address provided (xxx.xxx.xxx.39) invalid. Check if another software is using port 47808 on this network interface. If so, you can define multiple IP per interface. Or specify another IP using BAC0.lite(ip='IP/mask')

Process finished with exit code 1

For xxx.xxx.xxx.x48,  it shows: 

Traceback (most recent call last):
  File "C:\Users\mmg-yho\PycharmProjects\bac0_test\main.py", line 8, in <module>
    bacnet = BAC0.connect(ip='xxx.xxx.xxx.x48')
  File "C:\ProgramData\Anaconda3\lib\site-packages\BAC0\scripts\Complete.py", line 170, in __init__
    Lite.__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\BAC0\scripts\Lite.py", line 150, in __init__
    ip_addr = Address("{}/{}:{}".format(ip, mask, port))
  File "C:\ProgramData\Anaconda3\lib\site-packages\bacpypes\pdu.py", line 71, in __init__
    self.decode_address(args[0])
  File "C:\ProgramData\Anaconda3\lib\site-packages\bacpypes\pdu.py", line 190, in decode_address
    addrstr = socket.inet_aton(local_ip_addr)
OSError: illegal IP address string passed to inet_aton
2022-10-09 13:43:20,391 - INFO    | Starting BAC0 version 21.12.03 (Complete)
2022-10-09 13:43:20,391 - INFO    | Use BAC0.log_level to adjust verbosity of the app.
2022-10-09 13:43:20,391 - INFO    | Ex. BAC0.log_level('silence') or BAC0.log_level('error')
2022-10-09 13:43:20,391 - INFO    | Starting TaskManager

Process finished with exit code 1

Can I say that xxx.xxx.xxx.x47 is the correct IP for the device, but there is another software using port 47808, so I cannot connect?
And why the IP changed from xxx.xxx.xxx.x47 to xxx.xxx.xxx.39?

Thank you very much.

**Comment by ChristianTremblay** [comment]
illegal IP address string passed to inet_aton

this comes from the OS, are you sure you didn't type a wrong IP ?

**Comment by ChristianTremblay** [comment]
and yes, if a software already use port 47808 on a network interface, the socker is used and BAC0 won't work.

BAC0 acts as a BACnet device and must be On/alive/using the socket all the time.

**Comment by Ferkelcode** [comment]
> and yes, if a software already use port 47808 on a network interface, the socker is used and BAC0 won't work.
> 
> BAC0 acts as a BACnet device and must be On/alive/using the socket all the time.

When I first time used the code  `BAC0.connect`, everything worked fine. But now it doesn't work, did I need to disconnect/switch off something that I connected in the first time, to free the prot 47808?

**Comment by rtarpara** [comment]
Any help with below error? Not able to connect BAC0. Port 47808 is already free.

runfile('C:/Users/User1/.spyder-py3/temp.py', wdir='C:/Users/User1/.spyder-py3')
[09/14/24 22:41:22] INFO     2024-09-14 22:41:22,066 - INFO    |   notes.py:267
                             Starting Asynchronous BAC0 version                
                             2024.09.10 (Lite)                                 
                    INFO     2024-09-14 22:41:22,069 - INFO    |   notes.py:267
                             Using bacpypes3 version 0.0.98                    
                    INFO     2024-09-14 22:41:22,074 - INFO    |   notes.py:267
                             Use BAC0.log_level to adjust                      
                             verbosity of the app.                             
                    INFO     2024-09-14 22:41:22,078 - INFO    |   notes.py:267
                             Ex. BAC0.log_level('silence') or                  
                             BAC0.log_level('error')                           
                    INFO     2024-09-14 22:41:22,091 - INFO    |    Lite.py:164
                             Using ip : 192.168.201.15/24 on port              
                             47808 | broadcast : 192.168.201.255               
Traceback (most recent call last):

  File C:\ProgramData\anaconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\user1\.spyder-py3\temp.py:9
    bacnet = BAC0.connect(ip='192.168.201.15/24')

  File C:\ProgramData\anaconda3\Lib\site-packages\BAC0\scripts\Lite.py:168 in __init__
    Base.__init__(

  File C:\ProgramData\anaconda3\Lib\site-packages\BAC0\scripts\Base.py:130 in __init__
    raise InitializationError(

InitializationError: IP Address provided (192.168.201.15) invalid. Check if another software is using port 47808 on this network interface. If so, you can define multiple IP per interface. Or specify another IP using BAC0.lite(ip='IP/mask')

[09/14/24 22:41:22] INFO     2024-09-14 22:41:22,112 - INFO    |   notes.py:267
                             Installing recurring task Ping Task               
                             (id:2542739881952)
