### ISSUE TITLE
Cannot create two instances at the same time

### ISSUE THREAD

**Issue by dqcontrols** [ChristianTremblay/BAC0#358]
Hi, 

I am looking to create multiple RTUs (Rooftop Units) on a single Raspberry Pi as BACnet devices. I am running into the following error:

BAC0.core.io.IOExceptions.InitializationError: IP Address (10.0.0.10) already used by BAC0. Check if another software is using port 47808 on this network interface. If so, you can define multiple IP per interface. Or specify another IP using BAC0.lite(ip='IP/mask').

The raspberry Pi is on a Wi-Fi network that has the following ip address (10.0.0.10). 

The code I am running is as follows:

import BAC0
bacnet1 = BAC0.lite()
bacnet2 = BAC0.lite(ip = '10.0.0.10/24')

The error message is as follows:
Python 3.9.2 (/usr/bin/python3)
>>> %Run multiple_devices_test.py
2022-11-08 13:42:29,989 - INFO    | Starting BAC0 version 22.9.21 (Lite)
2022-11-08 13:42:29,990 - INFO    | Use BAC0.log_level to adjust verbosity of the app.
2022-11-08 13:42:29,991 - INFO    | Ex. BAC0.log_level('silence') or BAC0.log_level('error')
2022-11-08 13:42:29,991 - INFO    | Starting TaskManager
2022-11-08 13:42:30,091 - INFO    | Using ip : 10.0.0.10
2022-11-08 13:42:30,202 - INFO    | Starting app...
2022-11-08 13:42:30,204 - INFO    | BAC0 started
2022-11-08 13:42:30,205 - INFO    | Registered as Simple BACnet/IP App
2022-11-08 13:42:30,213 - INFO    | Update Local COV Task started
2022-11-08 13:42:30,214 - INFO    | Starting BAC0 version 22.9.21 (Lite)
2022-11-08 13:42:30,214 - INFO    | Use BAC0.log_level to adjust verbosity of the app.
2022-11-08 13:42:30,215 - INFO    | Ex. BAC0.log_level('silence') or BAC0.log_level('error')
2022-11-08 13:42:30,216 - INFO    | Using ip : 10.0.0.10
Traceback (most recent call last):
  File "/home/demandq/Desktop/multiple_devices_test.py", line 4, in <module>
    bacnet2 = BAC0.lite(ip = '10.0.0.10/24')
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/scripts/Lite.py", line 152, in __init__
    Base.__init__(
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/scripts/Base.py", line 138, in __init__
    raise InitializationError(
BAC0.core.io.IOExceptions.InitializationError: IP Address provided (10.0.0.10) already used by BAC0. Check if another software is using port 47808 on this network interface. If so, you can define multiple IP per interface. Or specify another IP using BAC0.lite(ip='IP/mask')
>>>

Any help would be appreciated. Thanks in advance!

**Comment by ChristianTremblay** [comment]
You must use different IP addresses. Your using the same. 
It is possible to give multiple IPs to the same NIC.

**Comment by dqcontrols** [comment]
> 

Hi Christian,

Thanks for the response. I did some research into how to set up multiple IPs to the Raspberry Pi wlan0. Here is the current ip address settings in my Pi, with the ip addresses in use in **bold**

demandq@raspberrypi:~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether b8:27:eb:dc:87:37 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:89:d2:62 brd ff:ff:ff:ff:ff:ff
    **inet 10.0.0.10/24 brd 10.0.0.255 scope global dynamic noprefixroute wlan0**
       valid_lft 86337sec preferred_lft 75537sec
    **inet 11.0.0.100/24 scope global wlan0**
       valid_lft forever preferred_lft forever
    inet6 fe80::27c2:c87b:fcea:dc5f/64 scope link
       valid_lft forever preferred_lft forever

My current code is:
bacnet = BAC0.connect(ip='10.0.0.10/24')
bacnet1 = BAC0.conenct(ip='11.0.0.100/24')

This should connect each instance shown above to a different IP address. However, this still runs into issues. Any insights? I do believe that the ip addresses in the Pi are being set correctly as far as I am aware.

The new error I encounter is as follows:
Python 3.9.2 (/usr/bin/python3)
>>> %Run RTU_sim_N4_BAC0.py
2022-11-09 14:10:01,422 - INFO    | Starting BAC0 version 22.9.21 (Complete)
2022-11-09 14:10:01,423 - INFO    | Use BAC0.log_level to adjust verbosity of the app.
2022-11-09 14:10:01,425 - INFO    | Ex. BAC0.log_level('silence') or BAC0.log_level('error')
2022-11-09 14:10:01,427 - INFO    | Starting TaskManager
2022-11-09 14:10:01,432 - INFO    | Using ip : 10.0.0.10
2022-11-09 14:10:01,596 - INFO    | Starting app...
2022-11-09 14:10:01,598 - INFO    | BAC0 started
2022-11-09 14:10:01,599 - INFO    | Registered as Simple BACnet/IP App
2022-11-09 14:10:01,607 - INFO    | Update Local COV Task started
2022-11-09 14:10:04,132 - INFO    | Server started : http://10.0.0.10:8111
 * Serving Flask app "BAC0.web.FlaskServer" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8111/ (Press CTRL+C to quit)
2022-11-09 14:10:04,251 - INFO    | 10.0.0.101 network number is 1000
2022-11-09 14:10:08,144 - INFO    | Found those networks : {1000}
2022-11-09 14:10:08,146 - INFO    | Discovering network 1000
2022-11-09 14:10:11,155 - INFO    | Starting BAC0 version 22.9.21 (Complete)
2022-11-09 14:10:11,157 - INFO    | Use BAC0.log_level to adjust verbosity of the app.
2022-11-09 14:10:11,158 - INFO    | Ex. BAC0.log_level('silence') or BAC0.log_level('error')
2022-11-09 14:10:11,159 - INFO    | Using ip : 11.0.0.100
2022-11-09 14:10:11,174 - INFO    | Starting app...
2022-11-09 14:10:11,178 - INFO    | BAC0 started
2022-11-09 14:10:11,179 - INFO    | Registered as Simple BACnet/IP App
2022-11-09 14:10:11,190 - INFO    | Update Local COV Task started
an error has occurred: no adapters
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/core.py", line 165, in run
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/service/device.py", line 32, in startup
    self.i_am()
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/service/device.py", line 133, in i_am
    self.request(iAm)
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/core/app/ScriptApplication.py", line 246, in request
    super(BAC0Application, self).request(apdu)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/app.py", line 485, in request
    super(ApplicationIOController, self).request(apdu)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/app.py", line 364, in request
    super(Application, self).request(apdu)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/comm.py", line 574, in request
    self.elementService.sap_indication(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/appservice.py", line 1508, in sap_indication
    self.request(xpdu)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/comm.py", line 574, in request
    self.elementService.sap_indication(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/appservice.py", line 1329, in sap_indication
    self.request(apdu)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/comm.py", line 282, in request
    self.clientPeer.indication(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bacpypes/netservice.py", line 334, in indication
    raise ConfigurationError("no adapters")
bacpypes.errors.ConfigurationError: no adapters
--- Logging error ---
Traceback (most recent call last):
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 57, in task
    self.startServer()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 38, in startServer
    self.server = Server(
  File "/usr/local/lib/python3.9/dist-packages/bokeh/server/server.py", line 426, in __init__
    sockets, self._port = bind_sockets(opts.address, opts.port)
  File "/usr/local/lib/python3.9/dist-packages/bokeh/server/util.py", line 73, in bind_sockets
    ss = netutil.bind_sockets(port=port or 0, address=address)
  File "/usr/local/lib/python3.9/dist-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 31, in run
    self.process()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 35, in process
    self.task()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 59, in task
    self._log.warning("Bokeh server already running", err)
Message: 'Bokeh server already running'
Arguments: (OSError(98, 'Address already in use'),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 57, in task
    self.startServer()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 38, in startServer
    self.server = Server(
  File "/usr/local/lib/python3.9/dist-packages/bokeh/server/server.py", line 426, in __init__
    sockets, self._port = bind_sockets(opts.address, opts.port)
  File "/usr/local/lib/python3.9/dist-packages/bokeh/server/util.py", line 73, in bind_sockets
    ss = netutil.bind_sockets(port=port or 0, address=address)
  File "/usr/local/lib/python3.9/dist-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 31, in run
    self.process()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 35, in process
    self.task()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/BokehServer.py", line 59, in task
    self._log.warning("Bokeh server already running", err)
Message: 'Bokeh server already running'
Arguments: (OSError(98, 'Address already in use'),)
2022-11-09 14:10:13,685 - INFO    | Server started : http://11.0.0.100:8111
 * Serving Flask app "BAC0.web.FlaskServer" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
error: uncaptured python exception, closing channel <bacpypes.task._Trigger connected at 0x719ceec8> (<class 'BlockingIOError'>:[Errno 11] Resource temporarily unavailable [/usr/lib/python3.9/asyncore.py|read|83] [/usr/lib/python3.9/asyncore.py|handle_read_event|420] [/usr/local/lib/python3.9/dist-packages/bacpypes/task.py|handle_read|41] [/usr/lib/python3.9/asyncore.py|recv|371] [/usr/lib/python3.9/asyncore.py|recv|600])
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/FlaskServer.py", line 163, in task
    self.startServer()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/FlaskServer.py", line 49, in startServer
    self.flask_app.run(port=self.port, host="0.0.0.0")
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/FlaskServer.py", line 42, in run
    self.process()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/FlaskServer.py", line 46, in process
    self.task()
  File "/home/demandq/.local/lib/python3.9/site-packages/BAC0/web/FlaskServer.py", line 165, in task
    self._log.warning("Flask server already running", err)
AttributeError: 'FlaskServer' object has no attribute '_log'
2022-11-09 14:10:17,690 - INFO    | Found those networks : set()
2022-11-09 14:10:17,692 - INFO    | No BACnet network found, attempting a simple whois using provided device instances limits (0 - 4194303)
>>>

**Comment by ChristianTremblay** [comment]
Use BAC0.lite instead of BAC0.connect
