### ISSUE TITLE
AttributeError in "bacnet = BAC0.connect()" full command

### ISSUE THREAD

**Issue by sourcebitt** [ChristianTremblay/BAC0#435]
after importing flask, flask_bootstrap, bokeh, pandas, BAC0, then running command "bacnet = BAC0.connect()":

`>>> bacnet = BAC0.connect()
2023-12-05 14:13:28,207 - INFO    | Starting BAC0 version 23.07.03 (Complete)
2023-12-05 14:13:28,208 - INFO    | Use BAC0.log_level to adjust verbosity of the app.
2023-12-05 14:13:28,208 - INFO    | Ex. BAC0.log_level('silence') or BAC0.log_level('error')
2023-12-05 14:13:28,209 - INFO    | Starting TaskManager
2023-12-05 14:13:28,239 - INFO    | Using ip : 192.168.8.199 on port 47808 | broadcast : 192.168.8.199
2023-12-05 14:13:28,251 - INFO    | Starting app...
2023-12-05 14:13:28,252 - INFO    | BAC0 started
2023-12-05 14:13:28,253 - INFO    | Registered as Simple BACnet/IP App
2023-12-05 14:13:28,254 - INFO    | Device instance (id) : 3056779
2023-12-05 14:13:28,258 - INFO    | Update Local COV Task started (required to support COV)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/BAC0-23.7.3-py3.11.egg/BAC0/scripts/Complete.py", line 183, in __init__
  File "/usr/local/lib/python3.11/dist-packages/BAC0-23.7.3-py3.11.egg/BAC0/scripts/Complete.py", line 222, in start_bokeh
  File "/usr/local/lib/python3.11/dist-packages/BAC0-23.7.3-py3.11.egg/BAC0/web/BokehRenderer.py", line 71, in __init__
  File "/usr/local/lib/python3.11/dist-packages/BAC0-23.7.3-py3.11.egg/BAC0/web/BokehRenderer.py", line 369, in create_figure
  File "/usr/local/lib/python3.11/dist-packages/bokeh/plotting/_figure.py", line 192, in __init__
    self._raise_attribute_error_with_matches(name, names | opts.properties())
  File "/usr/local/lib/python3.11/dist-packages/bokeh/core/has_props.py", line 375, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width
>>>`

Is there conflict due to boken being latest version?

**Comment by sourcebitt** [comment]
In file BokehRenderer.py changed "plot_width" to "width" and "plot_height" to "height", no issues now.

So in summary, in BAC0 version 23.07.03, in order to run without errors in "Complete" mode, you need to adjust BokehRenderer.py as above and also change "import Figure" to "import figure" as in previous issue.
