### ISSUE TITLE
Problem with write_weeklySchedule method (Any.encode() missing 1 required positional argument: 'self')

### ISSUE THREAD

**Issue by jucajata** [ChristianTremblay/BAC0#504]
While I was trying to overwrite one of my weekly Schedule I found an issue with the parametrization of the Any instance.

The code is:
```python
await bacnet_network.write_weeklySchedule(destination, schedule_instance, schedule)

destination: '10.xxx.xxx.xx'
schedule_instance: 2 (because the object name is "schedule 2")
schedule: {'states': {'inactive': 0, 'active': 1}, 'week': {'monday': [('9:45', 'active'), ('17:45', 'inactive')], 'tuesday': [('9:45', 'active'), ('17:45', 'inactive')], 'wednesday': [('9:45', 'active'), ('17:45', 'inactive')], 'thursday': [('9:45', 'active'), ('17:45', 'inactive')], 'friday': [('9:45', 'active'), ('17:45', 'inactive')], 'saturday': [('9:45', 'active'), ('17:45', 'inactive')], 'sunday': [('9:45', 'active'), ('17:45', 'inactive')]}}
```
How could I solve this issue with the BAC0==2024.9.20 version?

The complete Traceback:
```
Any.encode() missing 1 required positional argument: 'self'
2024-12-08 17:44:20,238 - INFO    | Installing recurring task Ping Task (id:2180480269680)
Exception in callback IPv4DatagramServer.set_local_transport_protocol(<IPv4Address 10.4.54.16>)(<Task cancell...nit__.py:150>>)
handle: <Handle IPv4DatagramServer.set_local_transport_protocol(<IPv4Address 10.4.54.16>)(<Task cancell...nit__.py:150>>)>  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
, in set_local_transport_protocol
    transport, protocol = task.result()
                          ^^^^^^^^^^^^^
  File "c:\Users\EFICIENCIACOLOMBIA\Documents\dev\GY_EE_BAC0\.venv\Lib\site-packages\bacpypes3\ipv4\__init__.py", line 159, in retrying_create_datagram_endpoint
    return await loop.create_datagram_endpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1445, in create_datagram_endpoint
    await waiter
```

**Comment by ChristianTremblay** [comment]
Thanks for pointing that out, I'll have alook

**Comment by ChristianTremblay** [comment]
Working on it...

**Comment by ChristianTremblay** [comment]
Please try the develop branch

**Comment by jucajata** [comment]
Hi Christian, I have tried to use the develop branch with the changes made, it does not generate any error and I get a message saying that the request has been sent to the controller to make the time change. I have sent the input parameters as they appear in the documentation, with the binary dictionary, and the days of the week. However, despite it saying that everything is correct, the changes are not reflected in the controller.

**Comment by ChristianTremblay** [comment]
Thanks for the feedback... I'll dig a little more

**Comment by ChristianTremblay** [comment]
I cannot replicate the issue

```
>>> hor = await bacnet.read_weeklySchedule('3:7', 10001)
>>> hor
{
    'object_references': [(<ObjectType: multi-state-value>, 10381)],
    'references_names': ['OCC-SCHEDULE'],
    'states': {'Occupied': 1, 'UnOccupied': 2, 'Standby': 3, 'Not Set': 4},
    'reliability': <Reliability: no-fault-detected>,
    'priority': 15,
    'presentValue': 'Occupied (1)',
    'week': {
        'monday': [('00:00', 'UnOccupied'), ('07:00', 'Occupied'), ('20:00', 'UnOccupied')],
        'tuesday': [('00:00', 'UnOccupied'), ('06:00', 'Occupied'), ('17:00', 'UnOccupied')],
        'wednesday': [('00:00', 'UnOccupied'), ('06:00', 'Occupied'), ('17:00', 'UnOccupied')],
        'thursday': [('00:00', 'UnOccupied'), ('06:00', 'Occupied'), ('17:00', 'UnOccupied')],
        'friday': [('00:00', 'UnOccupied'), ('06:00', 'Occupied'), ('17:00', 'UnOccupied')],
        'saturday': [('00:00', 'UnOccupied'), ('06:00', 'Occupied'), ('17:00', 'UnOccupied')],
        'sunday': [('00:00', 'UnOccupied'), ('06:00', 'Occupied'), ('17:00', 'UnOccupied')]
    }
}

>>> from BAC0.core.functions.Schedule import Schedule
>>> bacnet.write_weeklySchedule('3:7', 10001, hor2)    
>>> hor_b = await bacnet.read_weeklySchedule('3:7', 10001)  
>>> hor_b                                                                                                                                     
{                                                                                                                                             
    'object_references': [(<ObjectType: multi-state-value>, 10381)],                                                                          
    'references_names': ['OCC-SCHEDULE'],                                                                                                     
    'states': {'Occupied': 1, 'UnOccupied': 2, 'Standby': 3, 'Not Set': 4},                                                                   
    'reliability': <Reliability: configuration-error>,
    'priority': 15,
    'presentValue': 'Not Set (0)',
    'week': {
    'week': {
    'week': {
    'week': {
        'monday': [('01:00', 'Not Set'), ('17:00', 'Occupied')],
        'tuesday': [('02:00', 'Not Set'), ('17:00', 'Occupied')],
        'wednesday': [('03:00', 'Not Set'), ('17:00', 'Occupied')],
        'thursday': [('04:00', 'Not Set'), ('17:00', 'Occupied')],
        'friday': [('05:00', 'Not Set'), ('17:00', 'Occupied')],
        'saturday': [('06:00', 'Not Set'), ('17:00', 'Occupied')],
        'sunday': [('07:00', 'Not Set'), ('17:00', 'Occupied')]
    }
}
```

As you can see here I made it work on a JCI controller here. Can you give me more info about your issue ?

**Comment by ChristianTremblay** [comment]
wait... I overlooked the configuration error...

**Comment by ChristianTremblay** [comment]
Fixed https://github.com/ChristianTremblay/BAC0/commit/913f7c90182151f9510fdb1010c730dc052e6529
Can you try this ?

**Comment by ChristianTremblay** [comment]
Also ! don't use await for the write !
This function is synchronous... (yeah I know, it's hard to figure out...)

**Comment by jucajata** [comment]
This is all the code I have:

import BAC0
import asyncio
import socket
import psutil
from datetime import datetime
import calendar
import warnings
from sqlalchemy import create_engine, text
from dotenv import load_dotenv
import os
import sys

warnings.filterwarnings("ignore")  # Ignorar advertencias irrelevantes

# Cargar variables de entorno desde un archivo .env
load_dotenv()

class BACnetScheduler:
    def __init__(self, remote_ip, bbmdIP, bbmdTTL, port):
        self.remote_ip = remote_ip  # Nueva columna incluida
        self.bbmdIP = bbmdIP
        self.bbmdTTL = bbmdTTL
        self.port = port
        self.current_datetime = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        self.my_ip = f"{self.obtener_ip_privada_10()[0]}/24"
        self.data_records = []

    def obtener_ip_privada_10(self):
        ips_privadas = []
        for _, direcciones in psutil.net_if_addrs().items():
            for direccion in direcciones:
                if direccion.family == socket.AF_INET and direccion.address.startswith('10.'):
                    ips_privadas.append(direccion.address)
        if ips_privadas:
            return ips_privadas
        else:
            raise ValueError("No se encontró ninguna IP privada en el rango 10.x.x.x")

    async def run_bacnet(self):
        try:
            # Conexión a la red BACnet con BBMD usando un puerto específico
            bacnet_network = BAC0.connect(ip=self.my_ip, bbmdAddress=self.bbmdIP, bbmdTTL=self.bbmdTTL, port=self.port)

            # Realiza un descubrimiento de dispositivos
            devices = await bacnet_network.who_is()
            if not devices:
                print(f"No se encontraron dispositivos en la red con IP {self.remote_ip}.")
                return

            # Itera sobre los dispositivos y extrae detalles
            for device in devices:
                try:
                    device_id = device.iAmDeviceIdentifier[1]
                    pdu_source = str(device.pduSource)

                    # Leer el nombre del dispositivo, si está disponible
                    try:
                        device_name = await bacnet_network.read(f"{pdu_source} device {device_id} objectName")
                    except Exception:
                        device_name = None

                    # Lee la lista de objetos del dispositivo
                    try:
                        object_list = await bacnet_network.read(f"{pdu_source} device {device_id} objectList")

                        # Filtra objetos Schedule comparando con el tipo de objeto
                        schedule_objects = []
                        for obj in object_list:
                            try:
                                obj = str(obj)
                                obj_name, obj_num = obj.split(sep=',')
                                if obj_name == 'schedule':
                                    schedule_objects.append((obj_name, obj_num))
                            except ValueError:
                                continue

                        for obj_type, obj_id in schedule_objects:
                            # Construir dirección del objeto y leer propiedades
                            obj_address = f"{pdu_source} {obj_type} {obj_id}"
                            schedule_info = {
                                'remote_ip': self.remote_ip,  # Incluyendo remote_ip
                                'pdu_source': pdu_source,
                                'device_name': device_name,
                                'schedule_id': f"{obj_type} {obj_id}",
                                'object_name': None,
                            }
                            try:
                                # Leer el nombre del objeto Schedule (objectName)
                                try:
                                    object_name = await bacnet_network.read(f"{obj_address} objectName")
                                    schedule_info['object_name'] = object_name
                                except Exception:
                                    pass

                                # Leer el schedule semanal (weeklySchedule)
                                weekly_schedule = await bacnet_network.read(f"{obj_address} weeklySchedule")
                                if weekly_schedule is None:
                                    continue

                                # Iterar sobre los DailySchedule
                                for i, daily_schedule in enumerate(weekly_schedule):
                                    day_name = calendar.day_name[i]  # Obtener el nombre del día (Monday, Tuesday, etc.)
                                    if hasattr(daily_schedule, 'daySchedule'):
                                        day_schedule_entries = daily_schedule.daySchedule
                                        for idx, entry in enumerate(day_schedule_entries):
                                            valor = entry.value.get_value()
                                            estado = str(idx+1)
                                            if valor == 1:
                                                valor = 'ON'
                                            elif valor in (0, 2):
                                                valor = 'OFF'                                                
                                            registro = (
                                                self.remote_ip,
                                                pdu_source,
                                                device_name,
                                                schedule_info['schedule_id'],
                                                schedule_info['object_name'],
                                                i + 1,
                                                day_name,
                                                estado,
                                                str(entry.time),
                                                str(valor)
                                            )
                                            self.data_records.append(registro)

                            except Exception:
                                continue

                    except Exception:
                        continue

                except Exception:
                    continue

        except asyncio.CancelledError:
            print("La tarea fue cancelada.")
        except Exception as e:
            print(f"Error en la ejecución de BACnet: {e}")

        return self.data_records

    async def start(self):
        try:
            data_records = await self.run_bacnet()
            return data_records
        except Exception as e:
            print(f"Error en la ejecución del bucle de eventos: {e}")

    def write_schedule(self, device_address, schedule_object, weekly_schedule):
        """
        Escribe o actualiza los horarios de un objeto `schedule`.

        Args:
            device_address (str): Dirección BACnet del dispositivo (e.g., '2:5').
            schedule_object (str): Objeto schedule en formato 'schedule instance' (e.g., 'schedule 1').
            weekly_schedule (list): Lista de días y horarios con los valores deseados.
                Formato:
                    [
                        {'day': 'Monday', 'schedule': [{'time': '08:00:00', 'value': 'ON'}, ...]},
                        ...
                    ]
        """
        try:
            # Conexión a la red BACnet
            bacnet_network = BAC0.connect(ip=self.my_ip, bbmdAddress=self.bbmdIP, bbmdTTL=self.bbmdTTL, port=self.port)

            # Escribir la programación semanal
            bacnet_network.write_weeklySchedule(device_address, schedule_object, weekly_schedule)
            print(f"Horario actualizado exitosamente en {schedule_object} para {device_address}.")
        except Exception as e:
            print(f"Error al actualizar el horario en {device_address}: {e}")

async def main(operation, ip=None):
    """
    Método principal para ejecutar lectura o escritura según el parámetro de operación.

    Args:
        operation (str): Operación a realizar ('read' para lectura, 'write' para escritura).
        ip (str, optional): Dirección IP para la operación de escritura. Requerido solo para 'write'.
    """
    if operation == 'read':
        remote_ips = [
            '10.129.61.141',
        ]
        bbmdTTL = 600
        all_data_records = []

        for index, remote_ip in enumerate(remote_ips):
            bbmdIP = f'{remote_ip}:47808'
            port = 47808 + index
            scheduler = BACnetScheduler(remote_ip, bbmdIP, bbmdTTL, port)

            # Realizar lectura
            data_records = await scheduler.start()
            if data_records:
                all_data_records.extend(data_records)

        if all_data_records:
            # Guardar los registros leídos en la base de datos
            database_url = os.getenv('DATABASE_URL')
            engine = create_engine(database_url)

            try:
                with engine.begin() as connection:
                    insert_query = text("""
                        INSERT INTO eficiencia_energetica.estados_horarios_v2
                        (remote_ip, pdu_source, device_name, schedule_id, object_name, day, day_name, estado, hora, valor)
                        VALUES (:remote_ip, :pdu_source, :device_name, :schedule_id, :object_name, :day, :day_name, :estado, :hora, :valor)
                        ON CONFLICT (remote_ip, pdu_source, device_name, schedule_id, object_name, day, day_name, estado)
                        DO UPDATE SET
                            hora = EXCLUDED.hora,
                            valor = EXCLUDED.valor
                    """)
                    for record in all_data_records:
                        connection.execute(insert_query, {
                            'remote_ip': record[0],
                            'pdu_source': record[1],
                            'device_name': record[2],
                            'schedule_id': record[3],
                            'object_name': record[4],
                            'day': record[5],
                            'day_name': record[6],
                            'estado': record[7],
                            'hora': record[8],
                            'valor': record[9]
                        })
                    print("Datos guardados exitosamente en la base de datos.")
            except Exception as e:
                print(f"Error al guardar los datos en la base de datos: {e}")
        else:
            print("No se obtuvieron datos de los dispositivos.")

    elif operation == 'write':
        if not ip:
            print("Error: Para la operación de escritura, se debe proporcionar una IP.")
            sys.exit(1)

        ip = '10.129.61.141'
        bbmdIP = f'{ip}:47808'
        port = 47808
        scheduler = BACnetScheduler(ip, bbmdIP, 600, port)

        # Convierte el formato al requerido por BAC0
        bacnet_schedule = {}
        bacnet_schedule['states'] = {"inactive": 0, "active": 1}
        bacnet_schedule['week'] = {
                "monday": [("9:45", "active"),("17:45", "inactive")],
                "tuesday": [("9:45", "active"),("17:45", "inactive")],
                "wednesday": [("9:45", "active"),("17:45", "inactive")],
                "thursday": [("9:45", "active"),("17:45", "inactive")],
                "friday": [("9:45", "active"),("17:45", "inactive")],
                "saturday": [("9:45", "active"),("18:00", "inactive")],
                "sunday": [("9:45", "active"),("17:45", "inactive")],
                }

        # Escribir el horario en el dispositivo especificado
        scheduler.write_schedule('10.129.61.141:47808', 2, weekly_schedule=bacnet_schedule)
    else:
        print("Operación inválida. Usa 'read' o 'write'.")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Uso: python script.py <operation> [<ip>]")
        print("<operation>: 'read' o 'write'")
        print("<ip>: Dirección IP para 'write'. Requerido solo para esa operación.")
        sys.exit(1)

    operation = sys.argv[1]
    ip = sys.argv[2] if len(sys.argv) > 2 else None

    asyncio.run(main(operation, ip))

-------------------------------------------------------------------------------------------------------

And the logs are:
2025-01-29 21:25:04,026 - INFO    | Starting Asynchronous BAC0 version 2024.09.10 (Lite)
2025-01-29 21:25:04,079 - INFO    | Using bacpypes3 version 0.0.98
2025-01-29 21:25:04,080 - INFO    | Use BAC0.log_level to adjust verbosity of the app.
2025-01-29 21:25:04,080 - INFO    | Ex. BAC0.log_level('silence') or BAC0.log_level('error')
2025-01-29 21:25:04,379 - INFO    | Using ip : 10.4.54.26/24 on port 47808 | broadcast : 10.4.54.255
2025-01-29 21:25:04,581 - INFO    | Using default JSON configuration file
2025-01-29 21:25:04,621 - INFO    | Registering as a foreign device to host 10.129.61.141:47808 for 600 seconds
2025-01-29 21:25:04,628 - INFO    | Registered as BACnet/IP App | mode foreign
2025-01-29 21:25:04,633 - INFO    | Device instance (id) : 3057078
2025-01-29 21:26:09,575 - INFO    | **Schedule Write request sent to device : 10.129.61.141**
Horario actualizado exitosamente en 2 para 10.129.61.141:47808.
2025-01-29 21:28:32,316 - INFO    | Installing recurring task Ping Task (id:1320985105360)
Exception in callback IPv4DatagramServer.set_local_transport_protocol(<IPv4Address 10.4.54.26>)(<Task cancell...nit__.py:150>>)
handle: <Handle IPv4DatagramServer.set_local_transport_protocol(<IPv4Address 10.4.54.26>)(<Task cancell...nit__.py:150>>)>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\EFICIENCIACOLOMBIA\Documents\dev\GY_EE_BAC0\.venv\Lib\site-packages\bacpypes3\ipv4\__init__.py", line 176, in set_local_transport_protocol
    transport, protocol = task.result()
                          ^^^^^^^^^^^^^
  File "c:\Users\EFICIENCIACOLOMBIA\Documents\dev\GY_EE_BAC0\.venv\Lib\site-packages\bacpypes3\ipv4\__init__.py", line 159, in retrying_create_datagram_endpoint
    return await loop.create_datagram_endpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1445, in create_datagram_endpoint
    await waiter
asyncio.exceptions.CancelledError


---------------------------------------

But the Schedule is the same. What I'm doing wrong? I changed this line of code:

return Enumerated(dict_schedule["states"][v] - 1) 
with 
return Enumerated(dict_schedule["states"][v])

**Comment by jucajata** [comment]
If you want, we can make a call

**Comment by jucajata** [comment]
Thanks for all the support, the code works very good.
