### ISSUE TITLE
setup.py install....syntax error

### ISSUE THREAD

**Issue by F4u5t** [ChristianTremblay/BAC0#58]
C:\Users\Matt\python programming\BAC0-master\BAC0-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import BAC0.infos as infos
  File "C:\Users\Matt\python programming\BAC0-master (1)\BAC0-master\BAC0\__init__.py", line 4, in <module>
    from . import core
  File "C:\Users\Matt\python programming\BAC0-master (1)\BAC0-master\BAC0\core\__init__.py", line 3, in <module>
    from . import app
  File "C:\Users\Matt\python programming\BAC0-master (1)\BAC0-master\BAC0\core\app\__init__.py", line 3, in <module>
    from . import ScriptApplication
  File "C:\Users\Matt\python programming\BAC0-master (1)\BAC0-master\BAC0\core\app\ScriptApplication.py", line 30, in <module>
    from ..functions.debug import log_debug
  File "C:\Users\Matt\python programming\BAC0-master (1)\BAC0-master\BAC0\core\functions\__init__.py", line 3, in <module>
    from . import discoverPoints
  File "C:\Users\Matt\python programming\BAC0-master (1)\BAC0-master\BAC0\core\functions\discoverPoints.py", line 21, in <module>
    from ..devices.Points import EnumPoint, BooleanPoint, NumericPoint
  File "C:\Users\Matt\python programming\BAC0-master (1)\BAC0-master\BAC0\core\devices\__init__.py", line 3, in <module>
    from . import Device
  File "C:\Users\Matt\python programming\BAC0-master (1)\BAC0-master\BAC0\core\devices\Device.py", line 101
    def __init__(self, address, device_id, network, *, poll=10,
                                                     ^
SyntaxError: invalid syntax

**Comment by F4u5t** [comment]
figured it out
